### ISSUE TITLE
Keyboard shortcuts not entering

### ISSUE THREAD

**Issue by hash404** [TsunDoge/spotify-hotkeys-firefox#12]
I can enter F1-F12 but when I try and type in F13, it won't allow me.

**Comment by TsunDoge** [comment]
Firefox only support F1 to F12 function keys so that's why it doesn't work.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

Sorry but I can't do anything.
