### ISSUE TITLE
Shuffle and repeat

### ISSUE THREAD

**Issue by pintify** [TsunDoge/spotify-hotkeys-firefox#2]
Is it possible to add also shortcuts for shuffle and repeat? Maybe with "alt +shift + S" and "+ R"

**Comment by TsunDoge** [comment]
The `Alt+Shift+S` shortcut is not possible because Firefox have a shortcut with `Alt+S`. 
How about `Alt+Shift+F` for shuffle? @pintify

**Comment by pintify** [comment]
`Alt+Shift+F` works for me. My suggestions were mere examples.

I'll most likely modify them later if you implement the customization. Whenever possible I use something that matches visually such as `Alt +    z-x-c-v-b` (or a similar avoiding conflicts) as `shuffle-prev-play-next-repeat` in this case. Preferably usable with one hand.
