### ISSUE TITLE
Play-Pause of album

### ISSUE THREAD

**Issue by pintify** [TsunDoge/spotify-hotkeys-firefox#3]
I'm interested in a shortcut to press the green play-pause button in the playlists and albums. Is it possible to do using the current script? Possibly the shortcut need to be non-conflictive with the current play-pause

**Comment by TsunDoge** [comment]
Sorry I cannot understand what are you asking for. Which button are you referring to?

**Comment by pintify** [comment]
The green one that appears when you enter inside an album or a playlist:

Play:
![imagen](https://user-images.githubusercontent.com/31854894/36214239-3d32858e-11a9-11e8-890c-6b7d17a416df.png)
Pause:
![imagen](https://user-images.githubusercontent.com/31854894/36214244-4298e5e0-11a9-11e8-8a2d-d0d2e5cbe49c.png)

The identification in the source seems to be `<button class="btn btn-green"></button>`

**Comment by TsunDoge** [comment]
Oh that green one. The issue here is that the functionality of that button is the same as the play/pause of the bottom bar. However, if you want that button to behave as a way to change the album you are listening then I think it's better to use the mouse.

**Comment by pintify** [comment]
Well, I thought you would see no use in that, but had to try.
Just for the record, my particular use case is that while I'm listening a playlist, if I refresh the page (that gets stuck due to ads issues), the ordinary play-pause button makes no effect as there is no song on the go. The media player below appears empty.

**Comment by TsunDoge** [comment]
Okay, now I really understand why you want it. I can try something to "solve" that case but I promise nothing because is hard to test it.

**Comment by pintify** [comment]
No prob, any try is welcomed

**Comment by TsunDoge** [comment]
Done. I've created a new shortcut and it works BUT not sure if it will solve your issue with the ads.

**Comment by pintify** [comment]
It worked like a charm! Thanks for everything.
