### ISSUE TITLE
Show the shorcuts from the icon panel

### ISSUE THREAD

**Issue by piatra** [TsunDoge/spotify-hotkeys-firefox#4]
I needed this exact extension and it already exists, amazing!
How about showing the keybindings when you click the icon that gets added in the toolbar? I'd be happy to make a PR with this.

**Comment by TsunDoge** [comment]
Glad to read that 😄 

If you have any ideas or want to contribute feel free to do it! Any help would be appreciated.
It would be great to have a panel showing the shortcuts.

**Comment by TsunDoge** [comment]
@piatra I made some changes on your js code.

When I was trying to upload the new version, the EsLint warned about "unsafe assignments to innerHTML". On the above commit I solve it but maybe I broke something.
