### ISSUE TITLE
Setting MediaKeys

### ISSUE THREAD

**Issue by Ph1r3ph0x** [TsunDoge/spotify-hotkeys-firefox#6]
Hey :) Nice work with this extension :+1: 
When I am trying to set a different key combination though, I find that all options are greyed out. I also tried to change the defaults to the mediakeys in the manifest.json with no effect :man_facepalming: 
Do you know of any reason for this behavior? Thanks in advance :)

**Comment by TsunDoge** [comment]
Greetings.
I forgot to mention that you need at least Firefox 60 to modify the current shortcuts. So if you wish that functionality you can download a [nightly] (https://nightly.mozilla.org/ ) or [60+ developer edition] ( https://www.mozilla.org/en-US/firefox/channel/desktop/#developer ) build for your platform.
The other option is to download the addon from this repository, change the settings of the manifest.json and install it directly on your browser.

**Comment by Ph1r3ph0x** [comment]
Perfect, today my distro updated to 60.0.1 and everything works like a charm :) Very happy, thx =)
