### ISSUE TITLE
[request] option to not open Spotify

### ISSUE THREAD

**Issue by Geobert** [TsunDoge/spotify-hotkeys-firefox#8]
Hi, 

First of all, thank you for this really helpful extension :)

At the moment, if Spotify is not open and we hit a hotkey, it opens Spotify.
It is possible to add an option to not do anything if spotify is not already open?

**Comment by TsunDoge** [comment]
Hi,

Glad you like the extension :)

It behaviours like that because I find it useful when I want to open Spotify without having to type the url, but I can add a checkbox in the option page of the extension enabling/disabling this.

**Comment by Geobert** [comment]
Thank you for considering it!

My use case is `MediaPlayPause` affected and sometimes I'm using my local player and if ever I have focus on Firefox and hit Play to control this local player, I open Spotify as well ^^'

**Comment by PalmerChia** [comment]
我也有同样的需求，不希望在Spotify未打开的时候按热键自动打开Spotify，希望可以考虑加入这个限制

**Comment by TsunDoge** [comment]
I added a checkbox in the option page of the addon which enable/disable this feature. If you update the extension it should appear.

**Comment by Geobert** [comment]
Perfect! Thank you very much!
